finrl/model/models.py

updated models/model.py to allow for implementing custom policies

Custom Policy Learning

---

finrl/preprocessing/preprocessors.py

Changed the add_user_defined_feature from the default of adding daily returns to taking optimal name and function parameters that the user can define for any transformation of the data.
Fixed typo of calcualte_turbulence to calculate_turbulence.

added custom features to preprocessor, fixed typos

---

finrl/preprocessing/preprocessors.py

Reverts AI4Finance-LLC/FinRL-Library#29

Revert "added custom features to preprocessor, fixed typos"

---

FinRL_multiple_stock_trading.ipynb
finrl/preprocessing/preprocessors.py

add the intersection method to preprocess data

add the intersection method to preprocess data

---

FinRL_ensemble_multiple_stock_trading.ipynb
finrl/model/models.py

- Update ensemble strategy with this flow:
1) Train A2C, PPO, DDPG from `start_date` to `trade_date - rebalance_window - validation_window`
2) Choose the best model based on validation from  `trade_date - rebalance_window - validation_window  `to `trade_date - rebalance_window`
3) [**NEW STEP**] Retrain the chosen model from `start_date `to `trade_date - rebalance_window`
4) Use the retrained model and trade from  `trade_date - rebalance_window ` to `trade_date`
- Fix Turbulence Index Bug in run_ensemble_strategy
- Minor parameter input format changes in DRLEnsembleAgent class + notebook

Update ensemble strategy + Fix Turbulence Index Bug in run_ensemble_strategy

---

finrl/env/env_stocktrading_cashpenalty.py

Reverting per conversation with @louisowen6. 
These changes revert to previous state.

reverting changes in env.

---

.github/workflows/test.yml
README.md
docker/bin/build_container.sh
docker/bin/start_notebook.sh
docker/bin/test.sh
tests/test_marketdata/test_yahoodownload.py

* Implement tests (basic structure)
* Implement enhanced docker support
* Testing script to call tests!

Adding stubs for tests of major components.

---

finrl/env/env_stocktrading_cashpenalty.py
finrl/trade/backtest.py
tests/test_env/test_env_cashpenalty.py
tests/test_marketdata/test_yahoodownload.py

* Testing basic transactions
* Testing caching mechanism
* Stubbing out future tests that are required
* Formatting with black

Adding tests for cashpenalty

---

finrl/env/env_stocktrading_cashpenalty.py
tests/test_env/test_env_cashpenalty.py

Found bugs in `shares_increment` logic:
1) Negative actions should be added first with self.shares_increment
2) Actions clipping should be performed AFTER not BEFORE the rounding actions by shares_increment

Fix shares_increment bug & Add Tests Module

---

finrl/trade/backtest.py

Adding `trx_plot` function in `backtest.py` to plot buying and selling signal for each ticker during back-testing

Add trx_plot

---

finrl/env/env_stocktrading_stoploss.py

- Edit reward function
- Edit action constraints for stop-loss
Here are the evaluation results from `100 trials` of evaluation using different model random seeds. 
Details:
- `trading period`: 2019-01-01 until 2020-12-31
- `env`: StockTradingEnvStopLoss
- `model`: PPO
- `tickers`: ['AALI.JK', 'ITMG.JK', 'BBCA.JK','UNTR.JK', 'INKP.JK', 'JSMR.JK', 
'BBNI.JK', 'PTBA.JK', 'TOWR.JK', 'MDKA.JK', 'BTPS.JK']
- `features used`: ['turbulence','daily_variance', 'change', 'log_volume', 'close','day', 
'macd', 'rsi_30', 'cci_30', 'dx_30','close_prev_7','close_prev_14','close_prev_31']

[stoploss_env] Clean Code + Evaluation Results

---

finrl/tools/coin_search.py

Reverts AI4Finance-LLC/FinRL-Library#130

Revert "General data repo" for code maintenance purpose 

---

finrl/env/env_stocktrading_cashpenalty.py
finrl/env/env_stocktrading_stoploss.py

Issue #169 - Minor fix for environments for single stock 
@xiaoyang

Minor bug fix for issue #169

---

finrl/env/env_stocktrading.py

Cause L:116 makes self.state[index+self.stock_dim+1] into zero

Replace self.state[index+self.stock_dim+1] into sell_num_shares at env_stocktrading.py L:117

---

finrl/neo_finrl/env_stock_trading/env_stocktrading.py

Releated to https://github.com/AI4Finance-Foundation/FinRL/issues/277

Bug fix for single stock scenario

---

finrl/neo_finrl/preprocessor/preprocessors.py

Modified   finrl/neo_finrl/preprocessor/preprocessors.py

make full use of pandas

---

finrl/drl_agents/stablebaselines3/models.py

As we have refactored the codes, Carlogrisetti's PR cannot be merged automatically. Apply Carlogrisetti's changes to `finrl.drl_agents.stablebaselines3.models.py` to solve the conflict.

Carlogrisetti tensorboard logging

---

finrl/model/models.py

Add reward to tensorboard output logs

Add reward to tensorboard output logs

---

finrl/neo_finrl/preprocessor/yahoodownloader.py

As we have refactored the codes, Carlogrisetti's PR cannot be merged automatically. Apply Carlogrisetti's changes to `finrl.neo_finrl.preprocessor.yahoodownloader.py` to solve the conflict.

Carlogrisetti master

---

finrl/neo_finrl/preprocessor/tusharedownloader.py

tusharedownloader.py

---

finrl/drl_agents/stablebaselines3/models.py

Be able to revise the log directory when using stable-baselines3 models
Refer to issue #375

add tensorboard_log interface in sb3 models

---

finrl/apps/config.py

Ming add time zone

---

finrl/finrl_meta/preprocessor/yahoodownloader.py

it seems that this commit is missing.
see [this commit](https://github.com/AI4Finance-Foundation/FinRL/pull/71/commits/cac1cf1b3fb9022e10ec0ac4bc704d7fd6b3172b) and [this issue](https://github.com/AI4Finance-Foundation/FinRL/pull/71)

pass proxy to yahoo finance download method

---

FinRL_PaperTrading_Demo.ipynb

I have updated the Paper Trading DEMO with the latest changes from ElegantRL.

issues/441 : fix importing error from ElegantRL -> Argument Class

---

FinRL_Explainable_DRL_For_Portfolio_Management_An_Empirical_Approach.ipynb

To be consistent with the other notebooks in the repo root.

Add Colab link in notebook

---

finrl/drl_agents/elegantrl/models.py
finrl/finrl_meta/env_stock_trading/env_stock_papertrading.py
tutorials/3-Practical/FinRL_PaperTrading_Demo.ipynb

After the recent move in ElegantRL to remove a good chunk of duplicate
code, a lot of imports in various places including FinRL broke. Many
have asked about this on Slack as well. This commit should fix all those
imports to get the FinRL tutorials working again.

Fixed imports from elegantrl module

---

docs/source/developer/development_setup.rst
docs/source/index.rst

fixes #522
Add "development setup with PyCharm" to docs

Add "development setup with PyCharm" to docs

---

finrl/finrl_meta/data_processors/processor_alpaca.py

Code credit goes to @yizhangliu, thank you so much for your code!
The reason I'm creating this PR on behalf of sir yizhangliu is to save some time cuz I need the fix to continue on my sample

Update funciton that use deprecated v1 alpaca method to download bars

---

finrl/finrl_meta/env_stock_trading/env_stock_papertrading.py

Fixing Arguments class import that throw the following error

Fixing elegantrl Arguments class import

---

tutorials/4-Optimization/FinRL_HyperparameterTuning_Raytune_RLlib.ipynb

fix invalid notebook for Ray Tune

---

finrl/finrl_meta/env_stock_trading/env_stocktrading.py

@BruceYanghy  @spencerR1992  @XiaoYangLiu-FinRL 
This is to replace the PR #631 and fix the issue #630. Only line 158 is changed.

Bug fix to negative stock holding issue

---

finrl/config_private.py
finrl/finrl_meta/data_processor.py
finrl/main.py
finrl/train.py

1. Add a file: config_private.py
2. revise from finrl.train import to from train import train
or some errors like it.

Add config private, revise import

---

finrl/config_private.py
finrl/finrl_meta/data_processor.py
finrl/main.py
finrl/train.py

Reverts AI4Finance-Foundation/FinRL#650

Revert "Add config private, revise import"

---

.github/workflows/test.yml

updated test.yml to correct issue

---

finrl/meta/data_processors/processor_alpaca.py
tests/downloaders/test_alpaca_downloader.py

Related to https://github.com/AI4Finance-Foundation/FinRL/issues/685.

Download data with one query

---

Stock_NeurIPS2018_SB3.ipynb
finrl/meta/data_processors/processor_alpaca.py

repair ppo result dir

---

tutorials/3-Practical/FinRL_PaperTrading_Demo.ipynb

Changed ! to % to ensure package is created in home environment and not global.
See: https://github.com/microsoft/vscode-jupyter/wiki/Installing-Python-packages-in-Jupyter-Notebooks

Change to environment pip install

---

finrl/meta/data_processors/processor_yahoofinance.py

Align with PaperTrading_Demo requirements

Data Processor Yahoo Finance updates

---

tutorials/3-Practical/FinRL_PaperTrading_Demo.ipynb

Added code so when  if_vix = False it would switch to using calculated turbulence.

Adding conditional turbulence

---

tutorials/3-Practical/PaperTrading/FinRL_PaperTrading_Demo refactored.py

Convert FinRL_PaperTrading_Demo refactored.ipynb to .py and tidied up, as part of preparing to release into a production environment.

From ipynb to py

---

finrl/meta/paper_trading/alpaca.py
tutorials/FinRL_PaperTrading_Demo_refactored.py

Fixed a typo on an if statement.
Added ability to pass parameters of data provider and trading operations provider (broker)

Fix Alpaca typo and include broker parameters

---

README.md
finrl/agents/rllib/drllibv2.py

If the environment is already present in Rllib, then we don't need to specify the train and testing env

Updated drllibv2.py

---

finrl/meta/data_processors/processor_alpaca.py
finrl/meta/data_processors/processor_yahoofinance.py
finrl/meta/env_stock_trading/env_stocktrading.py
finrl/meta/env_stock_trading/env_stocktrading_np.py
finrl/meta/preprocessor/preprocessors.py
requirements.txt

https://github.com/AI4Finance-Foundation/FinRL/pull/862

processor_alpaca.clean_data fix for tickers data alignment. #862 - fix

---

finrl/meta/env_stock_trading/env_stocktrading_np.py

fix 870: remove broken import

---

docs/source/developer_guide/contributing.rst
docs/source/start/quick_start.rst

fix indentation in quick_start.rst code-block

---

pyproject.toml

See [this comment](https://github.com/AI4Finance-Foundation/FinRL/issues/915#issuecomment-1484160793) for details.

Add wrds as a dependency in pyproject.toml

---

finrl/config.py

Reverts AI4Finance-Foundation/FinRL#959

Revert "Revise config"

---

examples/Stock_NeurIPS2018_3_Backtest.ipynb

Update Stock_NeurIPS2018_3_Backtest.ipynb to Fix out of range exception

---

README.md

This fixes the links to the different sections accessible through the ToC.
@BruceYanghy @XiaoYangLiu-FinRL

Fix ToC section links.

---

finrl/meta/env_portfolio_allocation/env_portfolio.py

@bruceyang @spencerromo @xiaoyang
This PR updates the library from `gym` to `gymnasium` in `env_portifolio.py`. The team that has been maintaining `gym` has moved all future development to `gymnasium`, and `gym` will not be receiving any future updates. This change ensures our code remains up-to-date with the latest library developments.

Update gym to gymnasium in env_portifolio.py

---

finrl/agents/stablebaselines3/tune_sb3.py

imports for sb3 tuning file are outdated and cause compilation errors

fix imports tune_sb3.py

---

finrl/agents/stablebaselines3/models.py

@bruceyang @spencerromo @xiaoyang
I faced some difficulties when debugging the code, so I changed the try except for more specific exceptions.
1. Improved function signatures with type hints for clarity.
2. Enhanced variable initialization for efficiency.
3. Utilized a 'max_steps' variable for loop iteration.
4. Clarified early termination conditions with a descriptive message.
5. Introduced separation of concerns for code modularity.
6. Raised more specific exceptions for error handling.
7. Provided informative error messages for better debugging.
These changes optimize the code for readability, maintainability, and efficiency.

Incorporated optimizations and improvements

---

finrl/agents/elegantrl/models.py

There is a eleganrl model is not updated or snyc with updated or latest version of elegantrl. and So I have updated the file runs well for me I need suggestion or improvent that I can do in this file. 
Thank you

updated elegantrl agents for latest elegentrl release

---

finrl/agents/portfolio_optimization/architectures.py

Fix in_channels to use input_features instead of hard-coded 3.

---

finrl/meta/data_processors/processor_yahoofinance.py

Fix bug on Yahoo Finance Processor and solve confict problem in PR #849

Fix Bug on YahooFinanceProcessor

---

processor_sinopac.py
shioajidownloader.py

Data source from sinopac which is a taiwan stock platflom. Need API KEY !!! If something go wrong please contact me directly or common below

sinopac_datasource

---

example_of_shioaji_api.py
processor_sinopac.py
shioajidownloader.py

Add example of using shioajidownloader from sinopac data source. Fix the bug. It can work already. But Ram is require at least 16GB.

Add example of using shioajidownloader from sinopac data source

---

finrl/agents/stablebaselines3/models.py

PR to fix issue #1353 with regards to missing import in file [models.py](https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/agents/stablebaselines3/models.py)

Add missing import to agents/stablebaselines3/models.py

---

finrl/main.py
finrl/meta/data_processors/processor_yahoofinance.py
finrl/trade.py

This pull request includes the following changes: * Corrected Data Processing in `finrl/meta/data_processors/processor_yahoofinance.py`: Fixed an issue where 'open' and 'close' price columns were incorrectly swapped after data download from Yahoo Finance. * Improved Directory Handling in `finrl/main.py`: Modified the check_and_make_directories function to use absolute paths, improving reliability. * Reverted Commented Line in `finrl/trade.py`: As per your request, a previously removed commented-out line in finrl/trade.py has been restored.

fix: Data Processing and Pathing Improvements
