- finrl/env/env_stocktrading.py
1. Update action states if ` the current balance is not enough to buy new shares` or if `the current num of shares is less than the action state`
2. Bug fixing in `_sell_stock` function when the `turbulence_threshold ` is not `None`
3. Split `transaction_cost_pct `into 2 new parameters: `sell_cost_pct `and `buy_cost_pct`
> Update Action State, bug fixing in _sell_stock function, and Split transaction_cost_pct parameter

- finrl/marketdata/yahoodownloader.py
due to some reason, we can not download yahoo finance data directly, have to use a proxy, so I pass the proxy param to the fetch method, then it will be passed to yfinance's [download method](https://github.com/ranaroussi/yfinance/blob/master/yfinance/tickers.py#L71).
> pass proxy to yahoo finance download method

- finrl/env/env_stocktrading_cashpenalty.py
Add Features in env_stocktrading_cashpenalty.py:
1. Split `transaction_cost_pct` to `buy_cost_pct` and `sell_cost_pct`
2. Add optional actions discretization parameter: `discrete_actions`
3. Incorporate different length of data in multi stock trading
4. Minor fixing in class docs
5. Activate turbulence
6. Add `currency` parameter
7. Enrich logging information
8. Add optional `shares_increment` parameter. Now, we can handle the multiplies number of shares can be bought by using this parameter.
> (re-) Add New Features in Cash Penalty Environment 

- finrl/env/env_stocktrading_cashpenalty.py
- tests/test_env/test_env_cashpenalty.py
Add `patient` parameter to control whether we have to end the cycle when we're running out of cash or just don't buy anything until we got additional cash
> Add patient features in cash penalty env

- finrl/config/config.py
Hello !
French index CAC40 is a major index and it would be nice to have it directly defined in FinRL.
I propose to add it directly in config.py to make it available.
This list of CAC40 constituents is made as of 2019-01-01 like others FinRL tickers.
I added the source (a website maintained by a finance enthousiast) for the composition as there is no official source (Euronext) that gives old compositions of CAC40 at a specific date.
One symbol was part of the CAC40 on January 1, 2019 (Peugeot) and was delisted on January 17, 2020, following a merger (Peugeot became Stellantis after the merger with Fiat Chrysler). However, the new entity Stellantis (STLA.PA) has no pre-listing adjusted price for historization purposes on Yahoo Finance! Therefore, I propose, to ensure the continuity of the …
> Add French Index CAC40 to available tickers

- finrl/env/env_stocktrading_stoploss.py
This environment penalizes the model if exceeded the stop-loss threshold, selling assets with under expectation %profit, and also for not maintaining a reserve of cash.
Reward at any step is given as follows
`r_i = (sum(cash, asset_value) - total_penalty - initial_cash) / initial_cash / days_elapsed`
, where:
`total_penalty = cash_penalty + stop_loss_penalty + low_profit_penalty`
`cash_penalty = max(0, sum(cash, asset_value)*cash_penalty_proportion-cash)`
`stop_loss_penalty = -1 * dot(holdings,neg_closing_diff_avg_buy)`
`low_profit_penalty = -1 * dot(holdings,neg_profit_sell_diff_avg_buy)`
This reward function takes into account a profit/loss ratio constraint, liquidity requirement, as well as long-term accrued rewards.
This reward function also forces the model to trade only when it's …
> [New Environment] StopLoss Env

- finrl/preprocessing/preprocessors.py
Solving Issue [#186](https://github.com/AI4Finance-LLC/FinRL-Library/issues/186)
Fixing prev. implementation of `add_technical_indicator` function bug (time-series not matched)
Here's the output using prev. implementation. As you can see, it doesn't make sense that the lower band of Bollinger Band Indicator looks like that.
And here's the output using the revised function.
> Preprocessor Bug Fixing

- finrl/neo_finrl/data_processors/processor_alpaca.py
- finrl/neo_finrl/data_processors/processor_yahoofinance.py
- requirements.txt
- setup.py
trading_calenders has been marked unmaintained by developer. It is producing errors during build process on 3.9. Removed trading_calenders and replaced it with exchange_calenders
> Change from trading_calenders to exchange_calendars

- finrl/drl_agents/stablebaselines3/models.py
As an enthusiast, I decided to run the method proposed in this [paper ](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3690996) on my own BTCUSDT 1h dataset, during the execution  I realized that in case of the agent doesn't make any deals (like NOP forever), the daily return variable of the agent would remain constant and equal to `0` so the program would be interrupted with a `divided by zero` error [in this line](https://github.com/AI4Finance-Foundation/FinRL/blob/28b4be8f1b0949739a4371785aa68aa7b98124af/finrl/drl_agents/stablebaselines3/models.py#L214) . So I decided to check it beforehand in the `get_validation_sharpe` method.
>  fixing divided by zero error in .std() in get_validation_sharpe  

- .pre-commit-config.yaml
As stated in [Contributing Guidences](https://github.com/AI4Finance-Foundation/FinRL/blob/master/tutorials/Contributing.md), one should use pre-commit hooks. The origin `.pre-commit-config.yaml` has a restriction that python must be 3.6 while python 3.6 is not fully supported in this repo. So I simply remove this restriction.
> remove version restriction with `black`

- finrl/finrl_meta/env_stock_trading/env_stock_papertrading.py
- tutorials/3-Practical/FinRL_PaperTrading_Demo.ipynb
There are a couple of invalid import from AgentPPo in the source code, and one of them exist in the AlpacaPaperTrading class that throws the error ModuleNotFound, with this PR it will be fixed
Error that will be fixed
> Fixing invalid PPO import from elegantrl lib

- tutorials/4-Optimization/FinRL_HyperparameterTuning_Raytune_RLlib.ipynb
As per Ray 1.12.0, due to a system memory error issue using Google colab, these changes are proposed to resolve the errors
> Fix Ray tune error

- finrl/finrl_meta/env_stock_trading/env_stocktrading.py
Fix bug for issue: https://github.com/AI4Finance-Foundation/FinRL/issues/558 
`self.sell_cost_pct` is the cost list for all stocks, the index is missed, so error `TypeError: can't multiply sequence by non-int of type 'numpy.float64'` is raised when multiplied with other number. 
thx. @bruceyang @spencerromo @xiaoyang
> fix bug: self.sell_cost_pct is the list of costs

- requirements.txt
exchange-calendars 4.1.1 raise exception in `clean_data()`:
```
ValueError: Parameter `start` received with timezone defined as 'UTC' although a Date must be timezone naive.
```
It run with exchange-calendars 3.6.3.
I have added a restriction on exchange-calendars version.
> Restrict exchange-calendars version

- finrl/meta/data_processors/processor_alpaca.py
Fill nan price with 0 after basic cleaning step to avoid ValueError.
> Fix ValueError

- requirements.txt
While building the wheel, we need to first install the swig and then do pip install wheel
> Install swig for wheel building

- pyproject.toml
I am running Python 3.8.10 successfully, but the build of the finrl wheel recently has given an error:
ERROR: Package 'finrl-0.3.5' requires a different Python: 3.8.10 not in '>=3.7,<3.8'
Please can you extend the range
> Include python version <3.9

- finrl/meta/data_processors/processor_alpaca.py
- tutorials/FinRL_PaperTrading_Demo_refactored.py
Fix for https://github.com/AI4Finance-Foundation/FinRL/issues/770
The open and close trading times were an hour ahead of what they should be.
NYSE trading times are 14:30 - 20:59 UTC.
This caused the hstack() error in df_to_array() as the number of rows of prices per tic were not the same so arrays could not be stacked columnwise.
price_array = np.hstack(
[price_array, df[df.tic == tic][["close"]].values]
)
> Fix hstack issue   issue 770

- finrl/meta/data_processors/processor_yahoofinance.py
yahoo finance data is not accessible in China mainland, so i add a proxy which in supported in yfinance. You can pass a param which is the same as session param
> enable proxy when downloading yahoo finance data

- finrl/meta/env_cryptocurrency_trading/env_btc_ccxt.py
- finrl/meta/env_cryptocurrency_trading/env_multiple_crypto.py
- finrl/meta/env_portfolio_allocation/env_portfolio.py
- finrl/meta/env_stock_trading/env_nas100_wrds.py
- finrl/meta/env_stock_trading/env_stock_papertrading.py
- finrl/meta/env_stock_trading/env_stocktrading.py
- finrl/meta/env_stock_trading/env_stocktrading_cashpenalty.py
- finrl/meta/env_stock_trading/env_stocktrading_np.py
- finrl/meta/env_stock_trading/env_stocktrading_stoploss.py
- finrl/meta/paper_trading/alpaca.py
- finrl/meta/paper_trading/common.py
The "reset" function for each environment has been changed to match the gymnasium interface. This should address issues with external libraries that expect the full interface, such as stablebaselines3 and prevent such issues in future.
> Changed environment 'reset' interfaces to match the gymnasium interface.

- finrl/meta/env_stock_trading/env_stocktrading.py
Currently StockTradingEnv.reset() sets self.day to 0 after initializing state, which leads to incorrect state initialization as the state contains the stock prices of last day instead of the first day. This commit aims to fix this issue.
> Reset self.day before initializing state, otherwise self.state is incorrectly initialized when reset is called.

- docs/source/start/installation.rst
swig is needed for installation by default which is included in Ubuntu installation description but not the WSL
> Update installation.rst to add swig for WSL

- docs/source/finrl_meta/Benchmark.rst
Prior link pointed to an old link that does not exist anymore.
> Updated tutorial links in docs

- finrl/meta/preprocessor/preprocessors.py
Series.fillna is deprecated starting from pandas 2.1.0 and the recommended solution is available since the minimum version supported.
Info on the deprecation on https://pandas.pydata.org/docs/reference/api/pandas.Series.fillna.html
> Avoid deprecation warnings on pandas Series.fillna

- .gitignore
- finrl/meta/data_processor.py
- finrl/meta/data_processors/processor_alpaca.py
I performed some changes in the Alpaca download_data, clean_data, add_technical_indicators, and add_vix, which reduce the processing time by 80%. I tested the data sanity by running both data collecting and cleaning processes side by side and comparing them using this function:
```
def compare_data(data1, data2):
return data1.equals(data2)
is_equal = compare_data(data, data_downloaded)
print(f"The data is equal: {is_equal}")
(data == data_downloaded).all().all()
different_rows = data[data != data_downloaded].dropna(how='all')
print(different_rows)
len(data) == len(data_downloaded)
```
And it returned True. I also changed a line in the data_processor.py code to allow it to use my trainer code at https://github.com/mikazlopes/training-farm, which can cache the clean data to avoid repeating …
> improved Alpaca data process time

- finrl/agents/elegantrl/models.py
- finrl/meta/data_processors/processor_yahoofinance.py
function convert_interval(self, time_interval) 
suppose time_interval is 1d it will raise an error "wrong time_interval" So I have fixed it might be lower case r upper case
and when I download VIXY data then time_interval="1d" so it raise error. 
session_in_range variable takes Date type 
and it is my Date
when we use tz=pytz.UTC it raise error of timezone so it will be better to use `df = nyse.sessions_in_range(
pd.Timestamp(start), pd.Timestamp(end)
)`
or 
`df = nyse.sessions_in_range(
start, end
)
'
because Date takes both pd.Timestamps and str
> time interal condition and sessions in range changed

- examples/FinRL_PaperTrading_Demo.ipynb
- requirements.txt
I have submitted a similar pull request at [FinRL-Tutorials](https://github.com/AI4Finance-Foundation/FinRL-Tutorials). Still, I think it should also be updated here since more people might come here to view the `example` files, and are unaware of the tutorial repository.
---
An updated version of the `gymnasium` package changes the behavior of `gymnasium.Env.reset`. The return value of the reset method now returns a tuple of observation and info, which causes the tuple error mentioned in #1184 and #1164. Please refer to the [gymasium's documentation](https://gymnasium.farama.org/api/env/#gymnasium.Env.reset:~:text=Changed%20in%20version%20v0.25%3A%20The%20return_info%20parameter%20was%20removed%20and%20now%20info%20is%20expected%20to%20be%20returned.) for more details. This is fixed by …
> Fixing tuple, and 'UTC has no key' errors in examples/FinRL_PaperTrading_Demo.ipynb

- finrl/meta/preprocessor/yahoodownloader.py
Fixes https://github.com/AI4Finance-Foundation/FinRL/issues/1286
This pull request addresses an issue in yahoodownloader.py where the DataFrame downloaded from Yahoo contains multi-level column names, even though a single-level column structure is expected.
> Fix Multi-Level Column Names in DataFrame Downloaded using YahooDownloader

- finrl/meta/data_processors/processor_yahoofinance.py
Referring to #1290 , the same issue exists in processor_yahoofinance. After adding it, it works properly.
> Fix Multi-Level Column Names in DataFrame Downloaded using processor_yahoofinance.

- finrl/meta/preprocessor/yahoodownloader.py
The yFinance library only passes the Adj Close when auto_adjust is set to False. This pull request was created to address Issue #1300 by passing that parameter along with changing how the Pandas Dataframe renames the columns.
> Update renaming of columns from yfinance and passing auto_adjust as optional parameter

- pyproject.toml
- requirements.txt
- setup.py
#1313 
Currently, the pyproject.toml does not allow FinRL to be used in environments where the Python version exceeds 3.10. This change allows for FinRL to be installed in environments that use 3.11, like Google Colab [(Google Colab Blog Post)](https://medium.com/google-colab/colab-updated-to-python-3-11-00197d6172b1).
Please let me know if other items, such as unit tests, documentation, and build processes, need to be updated due to this change.
> Add support up to Python 3.11 for FinRL

- finrl/meta/data_processors/processor_yahoofinance.py
Summary
This pull request addresses an issue in the YahooFinanceProcessor where timestamps that were already timezone-aware (when you choose 1Min interval) were mistakenly processed using tz_localize(...), resulting in a TypeError (Cannot localize tz-aware Timestamp, use tz_convert for conversions). This fix ensures that timestamps with an existing timezone are handled correctly using tz_convert(...) instead.
Background
•	The original code applied tz_localize(...) without checking whether the timestamp was already tz-aware.
•	When the timestamp arrived with a UTC timezone (when you choose intraday interval for example), calling tz_localize(...) raised a TypeError.
•	This caused data processing to fail for certain records, particularly those retrieved from the Yahoo Finance API where …
> Fix timezone handling in YahooFinanceProcessor.

- pyproject.toml
- requirements.txt
This is the issue that keeps FinRL from building in Python 3.12.  pyfolio library is so old it is using functions that are deprecated in Python 3.12, specifically SafeConfigParser.
> Replace pyfolio with pyfolio-reloaded

- finrl/meta/preprocessor/yahoodownloader.py
- unit_tests/preprocessors/test_yahoodownloader.py
Calling `fetch_data(auto_adjust=True)` currently breaks because the yfinance adjusted df has no "Adj Close" column, as it has already been applied. Also, current implementation only adjusts close prices, whereas open high and low are returned raw, which means that any usage of these could be very wrong.
Example:
```py
df = YahooDownloader(
start_date='2010-01-01', end_date='2025-05-01', ticker_list=['AAPL', 'NVDA', 'AMZN', 'KHC']
).fetch_data(auto_adjust=True)
```
Error:
```py
KeyError                                  Traceback (most recent call last)
Cell In[142], line 3
1 df = YahooDownloader(
2     start_date='2010-01-01', end_date='2025-05-01', ticker_list=['AAPL', 'NVDA', 'AMZN', 'KHC']
----> 3 ).fetch_data(auto_adjust=True)
File …
```
> fix auto_adjust=True and adjust OHL as well in YahooDownloader

- finrl/agents/stablebaselines3/models.py
For example:
```
from stable_baselines3.common.callbacks import EvalCallback
[...]
eval_callback = EvalCallback(
env_backtest,
best_model_save_path=os.path.join(TRAINED_MODEL_DIR, model_name),
eval_freq=1,
deterministic=True,
render=False,
warn=False,
)
[...]
trained_a2c = agent.train_model(model=model_a2c, tb_log_name='a2c', total_timesteps=TIMESTEPS, callback=eval_callback)
```
This mantains the default TensorboardCallback(), and adds further ones if specified.
> Allow for custom callbacks to be passed to train_model
